include: package:lint/analysis_options.yaml

# Customize the rules depending on your needs. 

linter:
  rules:
    # Make constructors the first thing in every class
    sort_constructors_first: true

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true

    # Good packages document everything
    public_member_api_docs: false

    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: false

    # Back to the 80s
    lines_longer_than_80_chars: true

    # Use parameter order as in json response
    always_put_required_named_parameters_first: false

    # Util classes are awesome!
    avoid_classes_with_only_static_members: false

    avoid_bool_literals_in_conditional_expressions: false

analyzer:
  errors:
    argument_type_not_assignable: ignore
    invalid_assignment: ignore
    return_of_invalid_type_from_closure: ignore
    avoid_relative_lib_imports: error
    prefer_single_quotes: error
    unnecessary_await_in_return: error
    always_declare_return_types: warning
    file_names: ignore
    avoid_void_async: error
    sized_box_for_whitespace: warning
    lines_longer_than_80_chars: warning
    unused_local_variable: error
    prefer_const_literals_to_create_immutables: ignore
    
